// Generated by CoffeeScript 1.3.3

/*
module for displaying real time statistics from the optimization algorithm
*/


(function() {
  var Stats;

  Stats = (function() {

    function Stats() {}

    /*
    	configuration. Which stats modules should be anabled
    */


    Stats.prototype.configure = function() {};

    /*
    	Resets the module
    */


    Stats.prototype.reset = function() {};

    /*
    	Callback to called every time the new data arrives
    */


    Stats.prototype.feed = function(fitnessListInPopulation) {};

    return Stats;

  })();

  this.Stats = Stats;

}).call(this);
